\c study_db

-- Categories

INSERT INTO subjects
(subject)
VALUES
('Computer Science'),
('Accounting'),
('Business and Economics'),
('English'),
('Math'),
('Science');

-- Types

INSERT INTO types
(type)
VALUES
('multiple choice'),
('short answer'),
('true/false');

-- Worksheets
INSERT INTO worksheets
(name, subject_id)
VALUES
('Computer Fundamentals', 1),
('Operating Systems', 1),
('Sentence Completion', 4),
('Accounting Basics', 2),
('Math Problems', 5),
('Chemistry', 6),
('Business Law', 3);

-- Cards
INSERT INTO cards
(question, worksheet_id)
VALUES
('Which of the following languages is more suited to a structured program?', 1),
('A computer assisted method for the recording and analyzing of existing or hypothetical systems is', 1),
('The brain of any computer system is', 1),
('Any type of storage that is used for holding information between steps in its processing is', 1),
('A program component that allows structuring of a program in an unusual way is known as', 1),
('The radian of a number system', 1),
('Which type of system puts the user into direct conversation with the computer through a keyboard?', 1),
('The section of the CPU that selects, interprets and sees to the execution of program instructions', 1),
('The term referring to evacuating the content of some part of the machine is known as', 1),
('A single packet on a data link is known as', 1),
('Sockets are considered a high-level communications scheme', 2),
('The buddy system for allocating kernel memory is very likely to cause fragmentation within the allocated segments', 2),
('What is the correct order of operations for protecting a critical section using binary semaphore?', 2),
('One necessary condition for deadlock is _______, which states that a process must be holding one resource and waiting to acquire additional resources.', 2),
('_______ includes all of the file system structure, minus the actual contents of files.', 2),
('The difference between a program and a process is that a program is an active entity while a process is a passive entity.', 2),
('Which of the following statements is false?', 2),
('_______ occurs when a higher-priority process needs to access a data structure that is currently being accessed by a lower-priority process.', 2),
('The wait-for graph scheme is not applicable to a resource allocation system with multiple instances of each resource type.', 2),
('A significant problem with priority scheduling algorithms is _______.', 2),
('Rajeev failed in the examination because none of his answers were _______ to the questions asked.', 3),
('There are _______ views on the issue of giving bonus to the employees.', 3),
('"She was sorry she didn''t attend her friend''s wedding." "Yes, she _______"', 3),
('He behaves as if he _______ a king.', 3),
('The dog has been _______ by the car.', 3),
('_______ you apologize I shall punish you.', 3),
('We _______ start now to work for our examination.', 3),
('His boss _______ an explanation of his conduct with his colleagues.', 3),
('The artist had to _______ a lot before _______ recognized for his talent.', 3),
('Rama took his _______ for the wrong done to him.', 3),
('What is a general ledger account?', 4),
('What is the difference between accounts payable and accounts receivable?', 4),
('What are accruals?', 4),
('What is the distinction between debtor and creditor?', 4),
('What are examples of a general ledger acount?', 4),
('What are examples of a general ledger liability account?', 4),
('What is the cost of goods sold?', 4),
('How do I calculate the amount of sales tax that is included in total receipts?', 4),
('What is owner''s equity?', 4),
('What is petty cash?', 4),
('What is the cost of sales?', 4),
('The value of x + x(x<sup>x</sup>) when x = 2 is', 5),
('Mr. Jones sold two pipes at $1.20 each. Based on the cost, his profit one was 20% and his loss on the other was 20%. On the sale of the pipes, he', 5),
('A man has $ 10,000 to invest. He invests $ 4000 at 5 % and $ 3500 at 4 %. In order to have a yearly income of $ 500, he must invest the remainder at', 5),
('The distance light travels in one year is approximately 5,870,000,000,000 miles. The distance light travels in 100 years is', 5),
('Jones covered a distance of 50 miles on his first trip. On a later trip he traveled 300 miles while going three times as fast. His new time compared with the old time was', 5),
('If (0.2)<sup>x</sup> = 2 and log 2 = 0.3010, then the value of x to the nearest tenth is', 5),
('The fraction <sup>(5x-11)</sup>/<sub>(2x2 + x - 6)</sub> was obtained by adding the two fractions <sup>A</sup>/<sub>(x + 2)</sub> and <sup>B</sup>/<sub>(2x - 3)</sub>. The values of A and B must be, respectively', 5),
('The sum of three numbers is 98. The ratio of the first to the second is <sup>2</sup>/<sub>3</sub>, and the ratio of the second to the third is <sup>5</sup>/<sub>8</sub>. The second number is', 5),
('Two cities are 1580 miles apart. A plane leaves one of them traveling towards the other at an average speed o 400 mile per hour. At that time a plane leaves the other traveling towards the first at an average speed of 390 miles per hr. How long will it take them to meet?', 5),
('A table is three times as long as it is wide. If it were 5ft shorter and 5 ft wider it would be square (with all sides equal). How long and how wide is the table?', 5),
('I had $1.60 in dimes and nickels and had four more dimes then nickels. How many of both would I have?', 5),
('Randy has $15,000 that he would like to invest. He has a choice of two interest paying bonds, one offering a 4% annual interest and the other paying 8% annual interest. He would like to earn $760 in interest in one year using both types of bonds that he can put towards his vacation. How much money should he invest in each bond?', 5),
('The nucleus of an atom consists of', 6),
('The most electronegative element among the following is', 6),
('The metallurgical process in which a metal is obtained in a fused state is called', 6),
('The main use of salt in the diet is to', 6),
('The monomer of polythene is', 6),
('The luster of a metal is due to', 6),
('The most malleable metal is', 6),
('The oil used in the froth floatation process is', 6),
('Law made when an appellate court endorses a rule to be used in deciding court cases is', 7),
('_______ is a group of laws defining the methods for enforcing legal rights and decisions.', 7),
('_______ are enforced rules of conduct in a society.', 7),
('Laws enacted by state legislatures or federal legislatures are _______.
  ', 7),
('Status of a law that conflicts with a constitution and which is therefore invalid are _______.', 7),
('Power of the court to decide a case is called _______.', 7),
('Legislative enactments by a city are called _______.', 7),
('Government body formed to carry out particular laws are called _______.', 7),
('Basic fariness is also called _______.', 7),
('Power of a court to decide a case is called _______.', 7),
('The first ten amendments to the U.S. Constitution are known as the _______.', 7),
('As long as they are constitutionally valid, the laws of the various states', 7),
('_______ is law dictated from above.', 7),
('Sources of law include constitutions, statutes, cases decided by _______, and regulations and rulings of administrative agencies.', 7);

-- Options
INSERT INTO options
(card_id, type_id, option, isTrue)
VALUES
(1, 1, 'PL/1', false),
(1, 1, 'FORTRAN', false),
(1, 1, 'BASIC', false),
(1, 1, 'PASCAL', true),
(1, 1, 'None of the above', false),
(2, 1, 'Data transmission', false),
(2, 1, 'Data flow', true),
(2, 1, 'Data capture', false),
(2, 1, 'Data processing', false),
(2, 1, 'None of the above', false),
(3, 2, 'CPU', true),
(4, 1, 'CPU', false),
(4, 1, 'Primary storage', false),
(4, 1, 'Intermediate storage', true),
(4, 1, 'Internal storage', false),
(4, 1, 'None of the above', false),
(5, 2, 'Coroutine', true),
(6, 1, 'Is variable', false),
(6, 1, 'Has nothing to do with digit position value', false),
(6, 1, 'Equals the number of its distinct counting digits', true),
(6, 1, 'Is always an even number', false),
(6, 1, 'None of the above', false),
(7, 1, 'Real time processing', false),
(7, 1, 'Interactive computer', true),
(7, 1, 'Batch processing', false),
(7, 1, 'Time sharing', false),
(7, 1, 'None of the above', false),
(8, 2, 'Control unit', true),
(9, 2, 'Dump', true),
(10, 1, 'Path', false),
(10, 1, 'Frame', true),
(10, 1, 'Block', false),
(10, 1, 'Group', false),
(10, 1, 'None of the above', false),
(11, 3, 'False', true),
(12, 3, 'True', true),
(13, 1, 'release() followed by acquire()', false),
(13, 1, 'acquire() followed by release()', false),
(13, 1, 'wait() followed by signal()', true),
(13, 1, 'signal() followed by wait()', false),
(14, 1, 'hold and wait', true),
(14, 1, 'mutual exclusion', false),
(14, 1, 'circular wait', false),
(14, 1, 'no preemption', false),
(15, 2, 'Metadata', true),
(16, 3, 'False', true),
(17, 1, 'Swapping works in conjunction with virtual memory techniques.', false),
(17, 1, 'Some systems allow for multiple swap spaces (disks).', false),
(17, 1, 'Solaris only swaps pages of anonymous memory.', false),
(17, 1, 'Typically, entire processes are swapped into memory.', true),
(18, 1, 'Priority inversion', true),
(18, 1, 'Deadlock', false),
(18, 1, 'A race condition', false),
(18, 1, 'A critical section', false),
(19, 3, 'True', true),
(20, 2, 'Starvation', true),
(21, 1, 'allusive', false),
(21, 1, 'revealing', false),
(21, 1, 'pertinent', true),
(21, 1, 'referential', false),
(22, 1, 'independent', false),
(22, 1, 'divergent', true),
(22, 1, 'modest', false),
(22, 1, 'adverse', false),
(23, 1, 'regretted she can''t have gone', false),
(23, 1, 'was regretting she does not go', false),
(23, 1, 'will regret she didn''t go', false),
(23, 1, 'was regretting that she couldn''t go', true),
(24, 1, 'was', false),
(24, 1, 'were', true),
(24, 1, 'has', false),
(24, 1, 'had', false),
(25, 1, 'run out', false),
(25, 1, 'run over', true),
(25, 1, 'run into', false),
(25, 1, 'run for', false),
(26, 1, 'Until', false),
(26, 1, 'Unless', true),
(26, 1, 'Till', false),
(26, 1, 'None of these', false),
(27, 1, 'had better', false),
(27, 1, 'has better', false),
(27, 1, 'are better', false),
(27, 1, 'better', true),
(28, 1, 'called up', false),
(28, 1, 'called off', false),
(28, 1, 'called for', true),
(28, 1, 'called upon', false),
(29, 1, 'struggle, being', true),
(29, 1, 'toil, he', false),
(29, 1, 'practice, performing', false),
(29, 1, 'effort, he was', false),
(29, 1, 'strive, the', false),
(30, 1, 'avenge', false),
(30, 1, 'vengeance', false),
(30, 1, 'revenge', true),
(30, 1, 'ravage', false),
(31, 2, 'A general ledger account is an account or record used to sort and store balance sheet and income statement transactions.', true),
(32, 2, 'Accounts payable are amounts a company owes because it purchased goods or services on credit from a supplier or vendor. Accounts receivable are amounts a company has a right to collect because it sold goods or services on credit to a customer. Accounts payable are liabilities. Accounts receivable are assets.', true),
(33, 2, 'Accruals are adjustments for 1)  revenues that have been earned but are not yet recorded in the accounts, and 2) expenses that have been incurred but are not yet recorded in the accounts.', true),
(34, 2, 'A <em>debtor</em> is a person or enterprise that owes money to another party. A <em>creditor</em> is a person, bank, or other enterprise that has lent money or extended credit to another party.', true),
(35, 2, 'Examples of general ledger accounts include the asset accounts such as Cash, Accounts Receivable, Inventory, Investments, Land, and Equipment.', true),
(36, 2, 'Examples of the general ledger liability accounts include Notes Payable, Accounts Payable, Accrued Expenses Payable, and Customer Deposits.', true),
(37, 2, 'The cost of goods sold is the cost of the merchandise that a retailer, distributor, or manufacturer has sold.', true),
(38, 2, 'To calculate the sales tax that is included in a company''s receipts from items subject to sales tax, divide the receipts by 1 + the sales tax rate. For example, if the sales tax rate is 6%, divide the total amount of  receipts by 1.06. If the sales tax rate is 7.25%, divide the total receipts by 1.0725.', true),
(39, 2, 'Owner''s equity is one of the three main components of a sole proprietorship''s balance sheet and accounting equation. Owner''s equity represents the owner''s investment in the business minus the owner''s draws or withdrawals from the business plus the net income (or minus the net loss) since the business began.', true),
(40, 2, 'Petty cash is a small amount of cash on hand that is used for paying small amounts owed, rather than writing a check. Petty cash is also referred to as a petty cash fund.', true),
(41, 2, 'The cost of sales for a manufacturer is the cost of finished goods in its beginning inventory plus the cost of goods manufactured minus the cost of finished goods in ending inventory. The cost of sales for a retailer is the cost of merchandise in its beginning inventory plus the net cost of merchandise purchased minus the cost of merchandise in its ending inventory.', true),
(42, 1, '10', true),
(42, 1, '16', false),
(42, 1, '18', false),
(42, 1, '36', false),
(42, 1, '64', false),
(43, 1, 'broke even', true),
(43, 1, 'lost 4 cents', false),
(43, 1, 'gained 4 cents', false),
(43, 1, 'lost 10 cents', false),
(43, 1, 'gained 10 cents', false),
(44, 1, '6 % ', false),
(44, 1, '6.1 %', false),
(44, 1, '6.2 %', false),
(44, 1, '6.3 %', false),
(44, 1, '6.4 %', true),
(45, 1, '587 × 10<sup>8</sup> miles', false),
(45, 1, '587 × 10<sup>10</sup> miles', false),
(45, 1, '587 × 10<sup>-10</sup> miles', false),
(45, 1, '587 × 10<sup>12</sup> miles', true),
(45, 1, '587 × 10<sup>-12</sup> miles ', false),
(46, 1, 'three times as much', false),
(46, 1, 'twice as much', true),
(46, 1, 'the same', false),
(46, 1, 'half as much', false),
(46, 1, 'a third as much', false),
(47, 1, '-10.0', false),
(47, 1, '-0.5', false),
(47, 1, '-0.4', true),
(47, 1, '-0.2', false),
(47, 1, '10.0', false),
(48, 1, '5x, -11', false),
(48, 1, '-11, 5x', false),
(48, 1, '-1, 3', false),
(48, 1, '3, -1', true),
(48, 1, '5, -11', false),
(49, 1, '15', false),
(49, 1, '20', false),
(49, 1, '30', true),
(49, 1, '32', false),
(49, 1, '33', false),
(50, 2, '2 hours', true),
(51, 2, 'Length 15, Width 5', true),
(52, 2, 'Nickels 8, Dimes 12', true),
(53, 2, '$11000 at 4% and $4000 at 8%', true),
(54, 1, 'electrons and neutrons', false),
(54, 1, 'electrons and protons', false),
(54, 1, 'protons and neutrons', true),
(54, 1, 'All of the above', false),
(55, 1, 'sodium', false),
(55, 1, 'bromine', false),
(55, 1, 'fluorine', true),
(55, 1, 'oxygen', false),
(56, 1 ,'smelting', true),
(56, 1 ,'roasting', false),
(56, 1 ,'calcinations', false),
(56, 1 ,'froth floatation', false),
(57, 1, 'make the taste of food better', false),
(57, 1, 'produce in small amounts the hydrochloric acid required for the digestion of food', true),
(57, 1, 'ease the process of cooking', false),
(57, 1, 'increase the solubility of food particles in water', false),
(58, 1, 'vinyl chloride', false),
(58, 1, 'ethylene', true),
(58, 1, 'ethyl alcohol', false),
(58, 1, 'None of the above', false),
(59, 1, 'its high density', false),
(59, 1, 'its high polishing', false),
(59, 1, 'its chemical inertness', false),
(59, 1, 'presence of free electrons', true),
(60, 1, 'platinum', false),
(60, 1, 'silver', false),
(60, 1, 'iron', false),
(60, 1, 'gold', true),
(61, 1, 'coconut oil', false),
(61, 1, 'olive oil', false),
(61, 1, 'kerosene oil', false),
(61, 1, 'pine oil', true),
(62, 1, 'Common law', false),
(62, 1, 'Case law', true),
(62, 1, 'Administrative law', false),
(62, 1, 'None of the above', false),
(63, 1, 'Common law', false),
(63, 1, 'Administrative agencies', false),
(63, 1, 'Procedural law', true),
(63, 1, 'Case law', false),
(64, 1, 'Statutes', false),
(64, 1, 'Laws', true),
(64, 1, 'Morals', false),
(64, 1, 'Values', false),
(65, 1, 'Statutes', true),
(65, 1, 'Rules', false),
(65, 1, 'Property', false),
(65, 1, 'Decided by the judge', false),
(66, 1, 'Right', false),
(66, 1, 'Wrong', false),
(66, 1, 'Illegal', false),
(66, 1, 'Unconstitutional', true),
(67, 1, 'Equity', false),
(67, 1, 'Administrative', false),
(67, 1, 'Rights', false),
(67, 1, 'Jurisdiction', true),
(68, 1, 'Ordinances', true),
(68, 1, 'Order', false),
(68, 1, 'Curfews', false),
(68, 1, 'Judges laws', false),
(69, 1, 'Cabinets', false),
(69, 1, 'Secretaries', false),
(69, 1, 'Administrative agencies', true),
(69, 1, 'Juries', false),
(70, 1, 'Honest', false),
(70, 1, 'Morals', false),
(70, 1, 'Values', false),
(70, 1, 'Equity', true),
(71, 1, 'Order', false),
(71, 1, 'Rights', false),
(71, 1, 'Jurisdiction', true),
(71, 1, 'Decisions', false),
(72, 1, 'Declaration of Independance', false),
(72, 1, 'Bill of Rights', true),
(72, 1, 'Add-ons', false),
(72, 1, 'Constitutions overides', false),
(73, 1, 'Do have to be alike', false),
(73, 1, 'Do not have to be alike', true),
(74, 1, 'Heavenly law', false),
(74, 1, 'Ritual law', false),
(74, 1, 'Grace law', false),
(74, 1, 'Positive law', true),
(75, 1, 'Supreme courts', false),
(75, 1, 'Juvenile courts', false),
(75, 1, 'Family courts', false),
(75, 1, 'Appellate courts', true);

INSERT INTO users
(username, email, password_digest)
VALUES
('gjames', 'g@m.co', '$2b$12$pTfh9Aol7LBLhSX29jXyPOhHw65VR.ovW/mkqqmuEtGoFiVMjnhIy'),
('gkj', 'g@k.js', '$2b$12$sziEz.M4ASuQO52pGdcom.qUClle2xvjjD/UU9mBYFvAFto47n6IW');
